# Generated by Django 5.0.1 on 2024-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_inputcommand_response_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadexcel',
            name='column_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
